<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>weskoerber's phasmo-tracker</title>
    <link rel="stylesheet" href="./css/evidence_item.css"/>
    <script type="module" src="index.js"></script>
</head>
<body>
<div class="main">
    <div id="Current Game">
        <h1>Difficulty</h1>
        <div id="difficulty">
            <input type="checkbox" name="difficulty_amateur" id="difficulty_amateur" />
            <label for="difficulty_amateur">Amateur</label>

            <input type="checkbox" name="difficulty_intermediate" id="difficulty_intermediate" />
            <label for="difficulty_intermediate">Intermediate</label>

            <input type="checkbox" name="difficulty_professional" id="difficulty_professional" />
            <label for="difficulty_professional">Professional</label>
        </div>

        <h1 id="asdf">Timer</h1>
        <div id="timer">
            <p id="timer_counter">0:00</p>
            <input id="start_timer" type="button" value="Start">
            <input id="stop_timer" type="button" value="Stop">
        </div>

        <h1>About the Ghost</h1>
        <div id="about_ghost">
            <label for="ghost_name">Name:</label>
            <input id="ghost_name" type="text" name="ghost_name" />

            <p>Shy?</p>
        </div>

        <h1>Objectives</h1>
        <div id="objectives">
            <ol>
                <li>Ghost type</li>
                <li></li>
                <li></li>
                <li></li>
            </ol>
        </div>

        <h1>Evidence</h1>
        <div id="evidence_selector">
            <div class="evidence_item"><a>EMF 5</a></div>
            <div class="evidence_item"><a>Spirit Box</a></div>
            <div class="evidence_item"><a>Fingerprints</a></div>
            <div class="evidence_item"><a>Orbs</a></div>
            <div class="evidence_item"><a>Writing</a></div>
            <div class="evidence_item"><a>Freezing Temps</a></div>
            <div class="evidence_item"><a>DOTS</a></div>
        </div>

        <h1>Possible Ghosts</h1>
        <div id="possible_ghosts">

        </div>
    </div>
</div>
</body>
</html>